version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: EbayClone.API/Dockerfile
    container_name: ebayclone_api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:8080"
    
  mvc:
    build:
      context: .
      dockerfile: EbayClone.MVC/Dockerfile
    container_name: ebayclone_mvc
    depends_on:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - mvc

volumes:
  sqlserver_data:
